### ISSUE TITLE
centos7 with latest ansible fails

### ISSUE THREAD

**Issue by juju4** [neillturner/omnibus-ansible#12]
```
[root@default-centos-7-1484215336 ~]# pip install ansible   
Collecting ansible
  Using cached ansible-2.2.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-r0nQd_/ansible/setup.py", line 55, in <module>
        data_files=[],
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2306, in require
        items = working_set.resolve(reqs, env, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.9.0 (/usr/lib/python2.7/site-packages), Requirement.parse('six>=1.10.0'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-r0nQd_/ansible/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

adding ```pip install six --upgrade``` before ansible install solves this.

**Comment by neillturner** [comment]
would you like to do a PR. 
I assume say adding 
  pip install six --upgrade
before line 109 
  mkdir -p /etc/ansible/
will fix it

**Comment by neillturner** [comment]
thanks for the PR. hope it also works with earlier versions of ansible -)
